[Feat/159] 분리수거 탭바 (분리수거통에 따른 팝업)
TeamB-um/B-umiOS pull request #163
Opened 2021-08-18 07:00 UTC by jins0704

## 🌈 PR 요약
분리수거통 꽉 차 있으면 새로운 화면 뒤에 리워드 제공
분리수거통 꽉 차 있지 않으면 토스트 팝업 제공

#### 📌 변경 사항
에셋 추가 

##### 📸 ScreenShot

##### ✅ PR check list
```
- commit message가 적절한지 확인해주세요. 
- 마지막으로 Coding Convention을 준수했는지 확인해주세요.
- 적절한 branch로 요청했는지 확인해주세요.
- Assignees, Label을 붙여주세요.
- 가능한 이슈를 Link 해주세요.
- PR이 승인된 경우 해당 브랜치는 삭제해주세요.
```

#### Linked Issue
close #159

2021-08-18 08:44 UTC, leeinae requested changes

2021-08-18 08:44 UTC, leeinae commented on B-umiOS/B-umiOS/Source/Separate/ViewController/SeparatePresentPopUpViewController.swift
> +            make.top.equalToSuperview().inset(302 * SizeConstants.screenRatio)
top 레이아웃 제대로 나오나요? 
**302 * SizeConstants.screenRatio** <- 이거 비율이 / 375.0이라 가로 기준 비율인데 top은 화면 세로 비율이라서..!  
그냥 302로 해주시거나, equalToSuperview().multiplied(302.0 / 812.0)을 해보시면 어떨까 싶어요

2021-08-18 08:44 UTC, leeinae commented on B-umiOS/B-umiOS/Source/Separate/ViewController/SeparatePresentPopUpViewController.swift
> +            make.top.equalTo(presentImageView.snp.bottom).offset(21 * SizeConstants.screenRatio)
위랑 동일합니다아

2021-08-18 08:44 UTC, leeinae commented on B-umiOS/B-umiOS/Source/Separate/ViewController/SeparateToastViewController.swift
> +            make.height.equalTo(45 * SizeConstants.screenRatio)
얘 레이아웃 잡을 때 equalTo(toastLabel.snp.width).multiplied(45.0 / 182.0) 하시는 게 더 정확할 것 같습니다..!
위랑 동일하게 높이 값인데 375 비율로 나눠버려서 .. 괜찮으려나 모르겠어서ㅠ 확인 후 이상하면 알려주세요

2021-08-18 08:44 UTC, leeinae commented on B-umiOS/B-umiOS/Source/Separate/ViewController/SeparateViewController/SeparateViewController+Extension.swift
> +//                self.navigationController?.pushViewController(pushVC, animated: true)
안 쓰이는 주석 삭제 부탁드립니다!

2021-08-18 08:44 UTC, leeinae commented on B-umiOS/B-umiOS/Source/Separate/ViewController/SeparateViewController/SeparateViewController+Extension.swift
> +//                guard let pushVC = self.storyboard?.instantiateViewController(withIdentifier: SeparateDetailViewController.identifier) as? SeparateDetailViewController else { return }
여기 부분 코드 중복이 꽤 있어보여서 `if - else` 안으로 vc 구분 넣어주시고, 블록 밖으로 설정 부분이나 present 빼도 될 것 같아요..!

2021-08-18 08:50 UTC, jins0704 commented on B-umiOS/B-umiOS/Source/Separate/ViewController/SeparatePresentPopUpViewController.swift
> +            make.top.equalToSuperview().inset(302 * SizeConstants.screenRatio)
그렇게 새로 적용하겠습니당

2021-08-18 08:51 UTC, jins0704 commented on B-umiOS/B-umiOS/Source/Separate/ViewController/SeparateToastViewController.swift
> +            make.height.equalTo(45 * SizeConstants.screenRatio)
계속 저래왔는데.. 음 다시 알아봐야겠네요

2021-08-18 08:51 UTC, jins0704 commented on B-umiOS/B-umiOS/Source/Separate/ViewController/SeparateViewController/SeparateViewController+Extension.swift
> +//                self.navigationController?.pushViewController(pushVC, animated: true)
넵

2021-08-18 08:52 UTC, jins0704 commented on B-umiOS/B-umiOS/Source/Separate/ViewController/SeparateViewController/SeparateViewController+Extension.swift
> +//                guard let pushVC = self.storyboard?.instantiateViewController(withIdentifier: SeparateDetailViewController.identifier) as? SeparateDetailViewController else { return }
아하 확인햇습니다

2021-08-19 13:12 UTC, leeinae approved these changes

2021-08-19 13:13 UTC, merged