[Feat/179] 나의 글 무한스크롤
TeamB-um/B-umiOS pull request #182
Opened 2021-09-05 14:16 UTC by anyukyung

## 🌈 PR 요약
나의 글 무한스크롤

#### 📌 변경 사항
변경사항 및 주의 사항 (모듈 설치 등)을 적어주세요.

##### 📸 ScreenShot

##### ✅ PR check list
```
- commit message가 적절한지 확인해주세요. 
- 마지막으로 Coding Convention을 준수했는지 확인해주세요.
- 적절한 branch로 요청했는지 확인해주세요.
- Assignees, Label을 붙여주세요.
- 가능한 이슈를 Link 해주세요.
- PR이 승인된 경우 해당 브랜치는 삭제해주세요.
```

#### Linked Issue
close #179

2021-09-06 16:44 UTC, leeinae requested changes

2021-09-06 16:44 UTC, leeinae commented on B-umiOS/B-umiOS/Resource/Common/PopUp/DeletePopUpViewController.swift
> +    var parentDelegate: DeleteWritingsDelegate?
이거 왜 두 개 사용하시는..? 이유가 따로 있나여

2021-09-06 16:44 UTC, leeinae commented on B-umiOS/B-umiOS/Resource/Common/PopUp/DeletePopUpViewController.swift
여기가 안 쓰이는 부분인가염? kind 안 쓰이면 switch 아예 빼셔도 될 것 같네예

2021-09-06 16:44 UTC, leeinae commented on B-umiOS/B-umiOS/Source/MyPage/ViewController/FilterBottomSheetViewController/FilterBottmSheetViewController.swift
>      var delegate: ChangeWritingDataDelegate?
얘도 그냥 변수 하나로 두고.. 같이 쓰면 안되나요..?

2021-09-06 16:44 UTC, leeinae commented on B-umiOS/B-umiOS/Source/MyPage/ViewController/FilterBottomSheetViewController/FilterBottmSheetViewController.swift
> +        WritingService.shared.fetchWriting(page: "1", start_date: startDate, end_date: endDate, category_id: categoryID) { response in
이거 삭제 후에 무조건 1페이지 띄워줘서 page:"1"로 들어가는 것 맞나용

2021-09-06 16:44 UTC, leeinae commented on B-umiOS/B-umiOS/Source/MyPage/ViewController/MyWritingViewController/MyWritingViewController.swift
> +    var pagedWritingCount = 0
paged? 페이징된 글의 카운트..?를 말하나여?

2021-09-06 16:44 UTC, leeinae commented on B-umiOS/B-umiOS/Source/MyPage/ViewController/MyWritingViewController/MyWritingViewController.swift
> +    }
이거 혹시 viewDidLoad에서만 호출하는 함수면 그냥 프로퍼티 기본값으로 지정해주시고 여기 비워두셔도 될 것 같아요
왠지 코드 중복의 느낌이 강해서리

2021-09-06 18:33 UTC, anyukyung commented on B-umiOS/B-umiOS/Resource/Common/PopUp/DeletePopUpViewController.swift
이거는 분리수거함 삭제팝업인듯!

2021-09-06 18:33 UTC, anyukyung commented on B-umiOS/B-umiOS/Resource/Common/PopUp/DeletePopUpViewController.swift
> 여기가 안 쓰이는 부분인가염? kind 안 쓰이면 switch 아예 빼셔도 될 것 같네예

이거는 분리수거함 삭제팝업인듯!

2021-09-06 18:34 UTC, anyukyung commented on B-umiOS/B-umiOS/Source/MyPage/ViewController/FilterBottomSheetViewController/FilterBottmSheetViewController.swift
> +        WritingService.shared.fetchWriting(page: "1", start_date: startDate, end_date: endDate, category_id: categoryID) { response in
> 이거 삭제 후에 무조건 1페이지 띄워줘서 page:"1"로 들어가는 것 맞나용

요고는 그 필터 적용할때라 첨부터 띄워줘서 1이삼요!

2021-09-06 18:35 UTC, anyukyung commented on B-umiOS/B-umiOS/Source/MyPage/ViewController/MyWritingViewController/MyWritingViewController.swift
> +    var pagedWritingCount = 0
> paged? 페이징된 글의 카운트..?를 말하나여?

ㅋㅋ 콩글리시 제송^^..  근데 여러가지 시도 햇엇어가지고 얘 이제 안씀 지우도록 하것음..

2021-09-06 18:38 UTC, anyukyung commented on B-umiOS/B-umiOS/Source/MyPage/ViewController/MyWritingViewController/MyWritingViewController.swift
> +    }
> 이거 혹시 viewDidLoad에서만 호출하는 함수면 그냥 프로퍼티 기본값으로 지정해주시고 여기 비워두셔도 될 것 같아요
> 왠지 코드 중복의 느낌이 강해서리

원래 프로퍼티 기본값도 쟤네인데요 요함수는 viewWillAppear에서 호출되걸랑요?
이렇게 해주질 않으면 viewWillAppear될 때 작동이 뭔가 이상해서 일단은 일케 했는데
viewWillAppear 될 때마다 프로퍼티 기본값으로 초기화하는 방법을 모르겠삼요 ㅠ.ㅠ..

2021-09-06 18:45 UTC, anyukyung commented on B-umiOS/B-umiOS/Resource/Common/PopUp/DeletePopUpViewController.swift
> +    var parentDelegate: DeleteWritingsDelegate?
@leeinae 원래있던거 싹다 지우고 다시 짜면서 바ㄹ생한 실수갓아요 그냥 하나 지웠삼!

2021-09-07 06:38 UTC, leeinae approved these changes

2021-09-07 06:38 UTC, merged