[Feat/183]  마이페이지 설정 (서비스 이용약관, 개인정보 처리방침, 문의하기)
TeamB-um/B-umiOS pull request #185
Opened 2021-09-10 11:02 UTC by jins0704

## 🌈 PR 요약
해당 pr에서 작업한 내역을 적어주세요.

#### 📌 변경 사항
변경사항 및 주의 사항 (모듈 설치 등)을 적어주세요.

##### 📸 ScreenShot

##### ✅ PR check list
```
- commit message가 적절한지 확인해주세요. 
- 마지막으로 Coding Convention을 준수했는지 확인해주세요.
- 적절한 branch로 요청했는지 확인해주세요.
- Assignees, Label을 붙여주세요.
- 가능한 이슈를 Link 해주세요.
- PR이 승인된 경우 해당 브랜치는 삭제해주세요.
```

#### Linked Issue
close #183

2021-09-12 03:35 UTC, leeinae requested changes

2021-09-12 03:35 UTC, leeinae commented on B-umiOS/B-umiOS/Source/Setting/ViewController/SettingViewController/SettingViewController.swift
> +        case "비움 미화원 소개" :
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋTabGesture identifier가 한글인가요..?

2021-09-12 03:35 UTC, leeinae commented on B-umiOS/B-umiOS/Source/Setting/ViewController/SettingViewController/SettingViewController+Layout.swift
> +            createView(text: "문의하기", items: [btnLeftButton()]),
11-12번째 줄 주석 삭제해주실수!

2021-09-13 08:05 UTC, anyukyung commented on B-umiOS/B-umiOS/Source/Setting/ViewController/SettingViewController/SettingViewController.swift
> +        case "비움 미화원 소개" :
ㅇㅏ 개웃기네

2021-09-13 08:52 UTC, jins0704 commented on B-umiOS/B-umiOS/Source/Setting/ViewController/SettingViewController/SettingViewController+Layout.swift
> +            createView(text: "문의하기", items: [btnLeftButton()]),
넵

2021-09-13 08:54 UTC, jins0704 commented on B-umiOS/B-umiOS/Source/Setting/ViewController/SettingViewController/SettingViewController.swift
> +        case "비움 미화원 소개" :
개발 당시에 저 부분을 tableview가 아니라 스택 뷰 형식으로 되어있고 뷰를 누르면 그에 따라 동작해야되는데,
뷰 간의 차이를 둘 부분이 애매해서요... 그래서 일단 label 명으로 해두긴했는데 어떻게 하는게 좋을까요

2021-09-16 06:25 UTC, merged