[Feat/198] 그래프 레이아웃 관련 오류 수정
TeamB-um/B-umiOS pull request #199
Opened 2021-10-22 09:14 UTC by jins0704

## 🌈 PR 요약
SE와 같은 작은 화면에서 오토레이아웃이 제대로 적용이 안되는 오류가 있었습니다.
이 부분에 대해서 수정하고 기능도 다시 한번 점검했습니다.

#### 📌 변경 사항
변경사항 및 주의 사항 (모듈 설치 등)을 적어주세요.

##### 📸 ScreenShot

##### ✅ PR check list
```
- commit message가 적절한지 확인해주세요. 
- 마지막으로 Coding Convention을 준수했는지 확인해주세요.
- 적절한 branch로 요청했는지 확인해주세요.
- Assignees, Label을 붙여주세요.
- 가능한 이슈를 Link 해주세요.
- PR이 승인된 경우 해당 브랜치는 삭제해주세요.

#### Linked Issue
close #198

2021-10-22 09:28 UTC, leeinae requested changes

2021-10-22 09:28 UTC, leeinae commented on B-umiOS/B-umiOS/Source/Separate/Component/GraphView.swift
> +    var p = 100
이거 변수가 의미하는 바가 뭔가요? 쓰임이 명확한 이름이면 용도를 파악하기 더 쉬울 것 같습니다!!

2021-10-23 07:05 UTC, jins0704 commented on B-umiOS/B-umiOS/Source/Separate/Component/GraphView.swift
> +    var p = 100
Percent 계산할때 쓰이는 변수입니다. percent로 바꿀게유

2021-10-23 07:13 UTC, leeinae approved these changes

2021-10-23 07:13 UTC, leeinae commented
확인했습니다 👍

2021-10-24 11:54 UTC, merged